name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 with Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
        
      - name: Compile Java projects
        run: |
          mvn clean install -f analysis/pom.xml
          mvn clean install -f userLoginCollectData/pom.xml
          mvn clean install -f showData/pom.xml
          mvn clean install -f userAuthentication/pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Update Docker Compose file
        run: |
          sed -i "s|analysis-service:.*|analysis-service:\n    image: ${{ secrets.DOCKER_USERNAME }}/analysis-service:latest|" compose.yml
          sed -i "s|collect-service:.*|collect-service:\n    image: ${{ secrets.DOCKER_USERNAME }}/collect-service:latest|" compose.yml
          sed -i "s|showdata-service:.*|showdata-service:\n    image: ${{ secrets.DOCKER_USERNAME }}/showdata-service:latest|" compose.yml
          sed -i "s|authentication-service:.*|authentication-service:\n    image: ${{ secrets.DOCKER_USERNAME }}/authentication-service:latest|" compose.yml

      - name: Deploy Docker Compose
        run: docker-compose up -d
